//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.14 at 11:22:21 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.iam.es/repositorio", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package es.iam.check.analisisDespliegues.business.chequeos.model;
