//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.14 at 11:22:21 AM CEST 
//


package es.iam.check.analisisDespliegues.business.chequeos.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoNombreChequeos.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TipoNombreChequeos">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ChequeoExtensionArtefacto"/>
 *     &lt;enumeration value="ChequeosEstructura"/>
 *     &lt;enumeration value="ChequeosDescriptores"/>
 *     &lt;enumeration value="ChequeoArchivosNoPermitidosEAR"/>
 *     &lt;enumeration value="ChequeosFicherosTraza"/>
 *     &lt;enumeration value="ChequeoLibreriasDuplicadas"/>
 *     &lt;enumeration value="ChequeosContenidoWebXML"/>
 *     &lt;enumeration value="ChequeosContenidoApplicationXML"/>
 *     &lt;enumeration value="ChequeoExtensionEstaticos"/>
 *     &lt;enumeration value="ChequeoArchivosNoPermitidosEstaticos"/>
 *     &lt;enumeration value="ChequeoExtensionRecursos"/>
 *     &lt;enumeration value="ChequeoArchivosNoPermitidosRecursos"/>
 *     &lt;enumeration value="ChequeoLibreriasNoPermitidas"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TipoNombreChequeos")
@XmlEnum
public enum TipoNombreChequeos {

    @XmlEnumValue("ChequeoExtensionArtefacto")
    CHEQUEO_EXTENSION_ARTEFACTO("ChequeoExtensionArtefacto"),
    @XmlEnumValue("ChequeosEstructura")
    CHEQUEOS_ESTRUCTURA("ChequeosEstructura"),
    @XmlEnumValue("ChequeosDescriptores")
    CHEQUEOS_DESCRIPTORES("ChequeosDescriptores"),
    @XmlEnumValue("ChequeoArchivosNoPermitidosEAR")
    CHEQUEO_ARCHIVOS_NO_PERMITIDOS_EAR("ChequeoArchivosNoPermitidosEAR"),
    @XmlEnumValue("ChequeosFicherosTraza")
    CHEQUEOS_FICHEROS_TRAZA("ChequeosFicherosTraza"),
    @XmlEnumValue("ChequeoLibreriasDuplicadas")
    CHEQUEO_LIBRERIAS_DUPLICADAS("ChequeoLibreriasDuplicadas"),
    @XmlEnumValue("ChequeosContenidoWebXML")
    CHEQUEOS_CONTENIDO_WEB_XML("ChequeosContenidoWebXML"),
    @XmlEnumValue("ChequeosContenidoApplicationXML")
    CHEQUEOS_CONTENIDO_APPLICATION_XML("ChequeosContenidoApplicationXML"),
    @XmlEnumValue("ChequeoExtensionEstaticos")
    CHEQUEO_EXTENSION_ESTATICOS("ChequeoExtensionEstaticos"),
    @XmlEnumValue("ChequeoArchivosNoPermitidosEstaticos")
    CHEQUEO_ARCHIVOS_NO_PERMITIDOS_ESTATICOS("ChequeoArchivosNoPermitidosEstaticos"),
    @XmlEnumValue("ChequeoExtensionRecursos")
    CHEQUEO_EXTENSION_RECURSOS("ChequeoExtensionRecursos"),
    @XmlEnumValue("ChequeoArchivosNoPermitidosRecursos")
    CHEQUEO_ARCHIVOS_NO_PERMITIDOS_RECURSOS("ChequeoArchivosNoPermitidosRecursos"),
    @XmlEnumValue("ChequeoLibreriasNoPermitidas")
    CHEQUEO_LIBRERIAS_NO_PERMITIDAS("ChequeoLibreriasNoPermitidas"),
    @XmlEnumValue("Todos")
    Todos("Todos");
    private final String value;

    TipoNombreChequeos(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TipoNombreChequeos fromValue(String v) {
        for (TipoNombreChequeos c: TipoNombreChequeos.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
