//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.14 at 11:22:21 AM CEST 
//


package es.iam.check.analisisDespliegues.business.chequeos.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoChequeo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoChequeo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mensaje" type="{http://www.iam.es/repositorio}TipoMensaje"/>
 *         &lt;element name="reglas" type="{http://www.iam.es/repositorio}TipoReglas"/>
 *       &lt;/sequence>
 *       &lt;attribute name="tipo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nombre" type="{http://www.iam.es/repositorio}TipoNombreChequeos" />
 *       &lt;attribute name="descripcion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoChequeo", propOrder = {
    "mensaje",
    "reglas"
})
public class TipoChequeo {

    @XmlElement(required = true)
    protected TipoMensaje mensaje;
    @XmlElement(required = true)
    protected TipoReglas reglas;
    @XmlAttribute
    protected String tipo;
    @XmlAttribute
    protected TipoNombreChequeos nombre;
    @XmlAttribute
    protected String descripcion;

    /**
     * Gets the value of the mensaje property.
     * 
     * @return
     *     possible object is
     *     {@link TipoMensaje }
     *     
     */
    public TipoMensaje getMensaje() {
        return mensaje;
    }

    /**
     * Sets the value of the mensaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoMensaje }
     *     
     */
    public void setMensaje(TipoMensaje value) {
        this.mensaje = value;
    }

    /**
     * Gets the value of the reglas property.
     * 
     * @return
     *     possible object is
     *     {@link TipoReglas }
     *     
     */
    public TipoReglas getReglas() {
        return reglas;
    }

    /**
     * Sets the value of the reglas property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoReglas }
     *     
     */
    public void setReglas(TipoReglas value) {
        this.reglas = value;
    }

    /**
     * Gets the value of the tipo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipo(String value) {
        this.tipo = value;
    }

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link TipoNombreChequeos }
     *     
     */
    public TipoNombreChequeos getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoNombreChequeos }
     *     
     */
    public void setNombre(TipoNombreChequeos value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the descripcion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * Sets the value of the descripcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcion(String value) {
        this.descripcion = value;
    }

}
