//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.14 at 11:22:21 AM CEST 
//


package es.iam.check.analisisDespliegues.business.chequeos.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoMensaje complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoMensaje">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="incorrecto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="correcto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="avisos" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoMensaje", propOrder = {
    "incorrecto",
    "correcto",
    "avisos"
})
public class TipoMensaje {

    @XmlElement(required = true)
    protected String incorrecto;
    @XmlElement(required = true)
    protected String correcto;
    @XmlElement(required = true)
    protected String avisos;

    /**
     * Gets the value of the incorrecto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncorrecto() {
        return incorrecto;
    }

    /**
     * Sets the value of the incorrecto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncorrecto(String value) {
        this.incorrecto = value;
    }

    /**
     * Gets the value of the correcto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrecto() {
        return correcto;
    }

    /**
     * Sets the value of the correcto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrecto(String value) {
        this.correcto = value;
    }

    /**
     * Gets the value of the avisos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvisos() {
        return avisos;
    }

    /**
     * Sets the value of the avisos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvisos(String value) {
        this.avisos = value;
    }

}
