//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.14 at 11:22:21 AM CEST 
//


package es.iam.check.analisisDespliegues.business.chequeos.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoRegla complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoRegla">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ejemplo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="patronOCadena" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tipoComprobacion" type="{http://www.iam.es/repositorio}ValuesTipoComprobacion"/>
 *         &lt;element name="tratamientoMayusculas" type="{http://www.iam.es/repositorio}ValuesTratamientoMayusculas" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="tipo" type="{http://www.iam.es/repositorio}ValuesTipoRegla" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoRegla", propOrder = {
    "ejemplo",
    "patronOCadena",
    "tipoComprobacion",
    "tratamientoMayusculas"
})
public class TipoRegla {

    @XmlElement(required = true)
    protected String ejemplo;
    @XmlElement(required = true)
    protected String patronOCadena;
    @XmlElement(required = true)
    protected ValuesTipoComprobacion tipoComprobacion;
    protected ValuesTratamientoMayusculas tratamientoMayusculas;
    @XmlAttribute
    protected ValuesTipoRegla tipo;

    /**
     * Gets the value of the ejemplo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEjemplo() {
        return ejemplo;
    }

    /**
     * Sets the value of the ejemplo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEjemplo(String value) {
        this.ejemplo = value;
    }

    /**
     * Gets the value of the patronOCadena property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatronOCadena() {
        return patronOCadena;
    }

    /**
     * Sets the value of the patronOCadena property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatronOCadena(String value) {
        this.patronOCadena = value;
    }

    /**
     * Gets the value of the tipoComprobacion property.
     * 
     * @return
     *     possible object is
     *     {@link ValuesTipoComprobacion }
     *     
     */
    public ValuesTipoComprobacion getTipoComprobacion() {
        return tipoComprobacion;
    }

    /**
     * Sets the value of the tipoComprobacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValuesTipoComprobacion }
     *     
     */
    public void setTipoComprobacion(ValuesTipoComprobacion value) {
        this.tipoComprobacion = value;
    }

    /**
     * Gets the value of the tratamientoMayusculas property.
     * 
     * @return
     *     possible object is
     *     {@link ValuesTratamientoMayusculas }
     *     
     */
    public ValuesTratamientoMayusculas getTratamientoMayusculas() {
        return tratamientoMayusculas;
    }

    /**
     * Sets the value of the tratamientoMayusculas property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValuesTratamientoMayusculas }
     *     
     */
    public void setTratamientoMayusculas(ValuesTratamientoMayusculas value) {
        this.tratamientoMayusculas = value;
    }

    /**
     * Gets the value of the tipo property.
     * 
     * @return
     *     possible object is
     *     {@link ValuesTipoRegla }
     *     
     */
    public ValuesTipoRegla getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValuesTipoRegla }
     *     
     */
    public void setTipo(ValuesTipoRegla value) {
        this.tipo = value;
    }

}
