//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.14 at 11:22:21 AM CEST 
//


package es.iam.check.analisisDespliegues.business.chequeos.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ValuesTiposChequeos.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ValuesTiposChequeos">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ChequeoContenidoDescriptoresDespliegue"/>
 *     &lt;enumeration value="ChequeoExistenciaFicheros"/>
 *     &lt;enumeration value="ChequeoLibreriasDuplicadas"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ValuesTiposChequeos")
@XmlEnum
public enum ValuesTiposChequeos {

    @XmlEnumValue("ChequeoContenidoDescriptoresDespliegue")
    CHEQUEO_CONTENIDO_DESCRIPTORES_DESPLIEGUE("ChequeoContenidoDescriptoresDespliegue"),
    @XmlEnumValue("ChequeoExistenciaFicheros")
    CHEQUEO_EXISTENCIA_FICHEROS("ChequeoExistenciaFicheros"),
    @XmlEnumValue("ChequeoLibreriasDuplicadas")
    CHEQUEO_LIBRERIAS_DUPLICADAS("ChequeoLibreriasDuplicadas");
    private final String value;

    ValuesTiposChequeos(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ValuesTiposChequeos fromValue(String v) {
        for (ValuesTiposChequeos c: ValuesTiposChequeos.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
